Make more imported gltf models able to survive round-tripping through open3d
PolyCam/open3d pull request #8
Opened 2023-08-15 01:41 UTC by garywang

- fix some issues with meshes that have materials but no uvs (because the material just has a solid color)
- support materials that have a `KHR_materials_pbrSpecularGlossiness` `diffuseTexture` instead of a `pbrMetallicRoughness` `baseColorTexture`
- for files with a node hierarchy, combine transformations from ancestor nodes instead of only looking at transformations on the leaf nodes
- read in `metallicFactor` and `roughnessFactor` from `pbrMetallicRoughness`
- store gltf extensions for materials in `GltfExtras` and write them back out when saving, including any texture images they reference

2023-08-15 15:04 UTC, omri-polycam requested changes

2023-08-15 15:04 UTC, omri-polycam commented on open3d/io/file_format/FileGLTF.cpp
> +  std::vector<Eigen::Matrix4d> node_transforms(model.nodes.size(), Eigen::Matrix4d::Identity());
Check out `tinygltf::Model::scenes` and `tinygltf::Model::defaultScene`, that's how you determine with what is a root and what isn't.

2023-08-15 15:04 UTC, omri-polycam commented on open3d/io/file_format/FileGLTF.cpp
> +  auto stack = std::vector<size_t>();
Why isn't this whole algorithm just accomplished with simple recursion?

2023-08-23 21:04 UTC, garywang commented on open3d/io/file_format/FileGLTF.cpp
> +  std::vector<Eigen::Matrix4d> node_transforms(model.nodes.size(), Eigen::Matrix4d::Identity());
The spec allows for there to not be a default scene or any scenes at all: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#scenes

2023-08-23 21:07 UTC, garywang commented on open3d/io/file_format/FileGLTF.cpp
> +  auto stack = std::vector<size_t>();
Changed it to just recurse instead of using an explicit stack.

I was worried about stack overflow, but there's probably no need given there would have to be tens of thousands of nodes before that's possible.

2023-08-23 21:16 UTC, omri-polycam approved these changes

2023-08-23 22:44 UTC, merged